service: aws-python-flask-api-project

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.9
  apiGateway:
    binaryMediaTypes:
      - "*/*"

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline
